#!/bin/bash

# this runs a simple nextflow workflow
# that creates alignment(s) and then trees 
# from one or more sets of sequences 

nextflow run main.nf \
 -resume \
 -profile singularity \
 --fasta '../input/*CDS.fasta'
